# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'userapp1' do

  # For displaying touch input during demos

  # Required by RNFirebase
  pod 'Firebase', :subspecs => [
    'Core',
    'Auth',
    'Firestore'
  ]

  # Required by react-native
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  # Required by native-base 
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end